package upgrade

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gofurry/fiberx/internal/core"
	"github.com/gofurry/fiberx/internal/metadata"
	"github.com/gofurry/fiberx/internal/version"
)

func TestAssessCompatibleCleanAndPlan(t *testing.T) {
	manifestRoot := generatorRootForUpgrade(t)
	projectDir := generateProjectForUpgrade(t, manifestRoot, "light")

	withGeneratorIdentity(t, "v0.14.0", "phase14-current", func() {
		assessment, err := Inspect(projectDir, manifestRoot)
		if err != nil {
			t.Fatalf("Inspect() returned error: %v", err)
		}
		if assessment.DiffStatus != metadata.StatusClean {
			t.Fatalf("expected clean diff status, got %q", assessment.DiffStatus)
		}
		if assessment.CompatibilityLevel != LevelCompatible {
			t.Fatalf("expected compatible level, got %q", assessment.CompatibilityLevel)
		}

		plan, err := Plan(projectDir, manifestRoot)
		if err != nil {
			t.Fatalf("Plan() returned error: %v", err)
		}
		if len(plan.RecommendedSteps) != 1 || !strings.Contains(plan.RecommendedSteps[0], "无需升级动作") {
			t.Fatalf("expected no-op upgrade plan, got %#v", plan.RecommendedSteps)
		}
	})
}

func TestAssessManualReviewForLocalModified(t *testing.T) {
	manifestRoot := generatorRootForUpgrade(t)
	projectDir := generateProjectForUpgrade(t, manifestRoot, "light")

	readmePath := filepath.Join(projectDir, "README.md")
	readmeData, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatalf("read generated README: %v", err)
	}
	if err := os.WriteFile(readmePath, append(readmeData, []byte("\nlocal change\n")...), 0o644); err != nil {
		t.Fatalf("write local change README: %v", err)
	}

	withGeneratorIdentity(t, "v0.14.0", "phase14-current", func() {
		assessment, err := Inspect(projectDir, manifestRoot)
		if err != nil {
			t.Fatalf("Inspect() returned error: %v", err)
		}
		if assessment.DiffStatus != metadata.StatusLocalModified {
			t.Fatalf("expected local_modified diff status, got %q", assessment.DiffStatus)
		}
		if assessment.CompatibilityLevel != LevelManualReview {
			t.Fatalf("expected manual_review level, got %q", assessment.CompatibilityLevel)
		}
		if len(assessment.LocalModifiedFiles) == 0 || assessment.LocalModifiedFiles[0] != "README.md" {
			t.Fatalf("expected README.md in local modified files, got %#v", assessment.LocalModifiedFiles)
		}
	})
}

func TestAssessCompatibleForGeneratorDrift(t *testing.T) {
	originalRoot := generatorRootForUpgrade(t)
	generatorCopy := filepath.Join(t.TempDir(), "generator")
	copyDirForUpgrade(t, originalRoot, generatorCopy)

	baseReadmePath := filepath.Join(generatorCopy, "assets", "base", "service-base-cobra", "README.md.tmpl")
	baseReadmeData, err := os.ReadFile(baseReadmePath)
	if err != nil {
		t.Fatalf("read copied generator README template: %v", err)
	}
	updatedReadme := strings.Replace(string(baseReadmeData), "Generated by `fiberx`.", "Generated by `fiberx` (phase14 drift).", 1)
	if err := os.WriteFile(baseReadmePath, []byte(updatedReadme), 0o644); err != nil {
		t.Fatalf("write copied generator README template: %v", err)
	}

	projectDir := generateProjectForUpgrade(t, generatorCopy, "light")

	withGeneratorIdentity(t, "v0.14.0", "phase14-current", func() {
		assessment, err := Inspect(projectDir, originalRoot)
		if err != nil {
			t.Fatalf("Inspect() returned error: %v", err)
		}
		if assessment.DiffStatus != metadata.StatusGeneratorDrift {
			t.Fatalf("expected generator_drift diff status, got %q", assessment.DiffStatus)
		}
		if assessment.CompatibilityLevel != LevelCompatible {
			t.Fatalf("expected compatible level, got %q", assessment.CompatibilityLevel)
		}
		if len(assessment.GeneratorDriftFiles) == 0 || assessment.GeneratorDriftFiles[0] != "README.md" {
			t.Fatalf("expected README.md in generator drift files, got %#v", assessment.GeneratorDriftFiles)
		}
	})
}

func TestAssessBreakingForDowngrade(t *testing.T) {
	manifestRoot := generatorRootForUpgrade(t)
	projectDir := generateProjectForUpgradeWithIdentity(t, manifestRoot, "light", "v0.14.0", "phase14-generated")

	withGeneratorIdentity(t, "v0.13.0", "phase14-current", func() {
		assessment, err := Inspect(projectDir, manifestRoot)
		if err != nil {
			t.Fatalf("Inspect() returned error: %v", err)
		}
		if assessment.CompatibilityLevel != LevelBreaking {
			t.Fatalf("expected breaking level, got %q", assessment.CompatibilityLevel)
		}
		if len(assessment.BlockingIssues) == 0 || !strings.Contains(assessment.BlockingIssues[0], "lower than generated version") {
			t.Fatalf("expected downgrade blocking issue, got %#v", assessment.BlockingIssues)
		}
	})
}

func TestAssessBreakingWhenRecipeCannotBeRendered(t *testing.T) {
	manifestRoot := generatorRootForUpgrade(t)
	projectDir := generateProjectForUpgrade(t, manifestRoot, "light")

	projectManifest, err := metadata.LoadManifest(projectDir)
	if err != nil {
		t.Fatalf("LoadManifest() returned error: %v", err)
	}
	projectManifest.Recipe.Preset = "extra-light"
	projectManifest.Recipe.Logger = "zap"
	projectManifest.Recipe.DB = "sqlite"
	projectManifest.Recipe.DataAccess = "stdlib"
	if err := metadata.WriteManifest(projectDir, projectManifest); err != nil {
		t.Fatalf("WriteManifest() returned error: %v", err)
	}

	withGeneratorIdentity(t, "v0.14.0", "phase14-current", func() {
		assessment, err := Inspect(projectDir, manifestRoot)
		if err != nil {
			t.Fatalf("Inspect() returned error: %v", err)
		}
		if assessment.CompatibilityLevel != LevelBreaking {
			t.Fatalf("expected breaking level, got %q", assessment.CompatibilityLevel)
		}
		if assessment.DiffStatus != DiffStatusUnavailable {
			t.Fatalf("expected unavailable diff status, got %q", assessment.DiffStatus)
		}
		if len(assessment.BlockingIssues) == 0 || !strings.Contains(strings.Join(assessment.BlockingIssues, "\n"), "does not support logger option") {
			t.Fatalf("expected unsupported recipe blocking issue, got %#v", assessment.BlockingIssues)
		}
	})
}

func generateProjectForUpgrade(t *testing.T, manifestRoot, preset string) string {
	t.Helper()

	return generateProjectForUpgradeWithIdentity(t, manifestRoot, preset, "v0.13.0", "phase13-generated")
}

func generateProjectForUpgradeWithIdentity(t *testing.T, manifestRoot, preset, generatorVersion, generatorCommit string) string {
	t.Helper()

	targetDir := t.TempDir()
	withGeneratorIdentity(t, generatorVersion, generatorCommit, func() {
		summary, err := core.Run(core.Request{
			ProjectName: "demo",
			ModulePath:  "github.com/example/demo",
			Preset:      preset,
			Options: map[string]string{
				"manifest_root": manifestRoot,
				"target_dir":    targetDir,
			},
		})
		if err != nil {
			t.Fatalf("Run() returned error: %v", err)
		}
		if summary.MetadataPath != ".fiberx/manifest.json" {
			t.Fatalf("expected metadata path in summary, got %q", summary.MetadataPath)
		}
	})
	return targetDir
}

func generatorRootForUpgrade(t *testing.T) string {
	t.Helper()

	root, err := filepath.Abs(filepath.Join("..", "..", "generator"))
	if err != nil {
		t.Fatalf("resolve manifest root: %v", err)
	}
	return root
}

func withGeneratorIdentity(t *testing.T, generatorVersion, generatorCommit string, fn func()) {
	t.Helper()

	previousVersion := version.Version
	previousCommit := version.Commit
	version.Version = generatorVersion
	version.Commit = generatorCommit
	defer func() {
		version.Version = previousVersion
		version.Commit = previousCommit
	}()

	fn()
}

func copyDirForUpgrade(t *testing.T, sourceDir, targetDir string) {
	t.Helper()

	if err := filepath.Walk(sourceDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(sourceDir, path)
		if err != nil {
			return err
		}
		targetPath := filepath.Join(targetDir, rel)
		if info.IsDir() {
			return os.MkdirAll(targetPath, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
			return err
		}
		return os.WriteFile(targetPath, data, 0o644)
	}); err != nil {
		t.Fatalf("copy directory %q to %q: %v", sourceDir, targetDir, err)
	}
}

func TestAssessmentJSONShape(t *testing.T) {
	assessment := Assessment{
		ProjectDir:         "demo",
		GeneratedGenerator: metadata.GeneratorInfo{Version: "v0.13.0", Commit: "abc"},
		CurrentGenerator:   metadata.GeneratorInfo{Version: "v0.14.0", Commit: "def"},
		Recipe:             metadata.Recipe{Preset: "light"},
		DiffStatus:         metadata.StatusClean,
		CompatibilityLevel: LevelCompatible,
		Reasons:            []string{"ok"},
	}

	data, err := json.Marshal(assessment)
	if err != nil {
		t.Fatalf("Marshal() returned error: %v", err)
	}
	if !strings.Contains(string(data), `"compatibility_level":"compatible"`) {
		t.Fatalf("expected compatibility level in JSON, got %s", string(data))
	}
}
